### ISSUE TITLE
Site formatting is broken?

### ISSUE THREAD

**Issue by amyhickman** [WillSullivan/idownvotedbecause#55]
Something happened to all the formatting on the site.  

    Being unresponsive {::comment}
    [People who read questions often leave comments seeking clarification. Without responding to these clarification requests, it is less likely that the question will be answered and you may get downvoted.](http://idownvotedbecau.se/beingunresponsive)
    {:/}

[Screenshot](https://imgur.com/VcnlMu9)

**Comment by tripleee** [comment]
I can concur. I thought the leaking Markdown was a site feature I was not yet fully understanding but now that I have looked a the sources, I can see that this is quite unlikely to be intentional.

In more detail, on the main page, each one of the reasons is followed by the verbatim text `{::comment}`; and many of the reasons are followed by more or less useless verbatim Markdown repeating the bullet point in an indented block, like

   * [Image of an exception](http://idownvotedbecau.se/imageofanexception/) {::comment}
    \[](http\://idownvotedbecau.se/imageofanexception/)
{:/}

(Reconstructed in actual Markdown here just for visibility.)

**Comment by tripleee** [comment]
Seems to be caused by, or at least pertinent to, https://github.com/WillSullivan/idownvotedbecause/issues/17#issuecomment-356286393

**Comment by Stargateur** [comment]
Same problem on chrome 63.0.3239.132

**Comment by tripleee** [comment]
I don't think this depends on the browser, but for what it's worth, I see this too in Firefox Nightly 59.0a1 and Safari 11.0.2 (13604.4.7.1.6) too (MacOS High Sierra).

**Comment by WillSullivan** [comment]
Yeah, I borked it.  Not sure why the comment syntax isn't working. Lemme see if I can fix.

**Comment by WillSullivan** [comment]
b5497616cf16ced371f0b9a79bcbe18842618b14 fixes.  I'm not sure why comments aren't allowed in that context.  Mostly because the Jekyll docs aren't helpful (I can't even locate where comment syntax is documented). Thanks, all.
