### ISSUE TITLE
Homework assignment

### ISSUE THREAD

**Issue by zlaKad** [WillSullivan/idownvotedbecause#73]
You should do your homework alone.

**Comment by byxor** [comment]
I think it's fine to ask for help on assignments as long as...

1. You've attempted to solve the problem.
2. You've researched the problem.
3. You present what you expect to happen and what actually happens.

Opinion: it's a bit harsh to downvote all questions that are based on homework assignments.

**Comment by WillSullivan** [comment]
Homework in general is fine, as long as they follow the required quality standards. Many issues with quality are already covered and can apply to a homework question, if appropriate. The one problem that only homework questions have--where the student dumps their homework problem verbatim into a question and expects others to complete it for them--can't be helped by a page here. The only solution for these questions is to delete them. You could suggest they try something and come back if they have a problem, but I think the chances of that happening are roughly zero. And since adding pages for problems that can't really be fixed is specifically not a goal of this website, I'll have to pass on this suggestion.

Sorry.
