### ISSUE TITLE
Could we have a page for the "XY Problem"?

### ISSUE THREAD

**Issue by sonic1981** [WillSullivan/idownvotedbecause#77]
For those that don't know what the XY problem is [outlined here](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

**Comment by WillSullivan** [comment]
Meh, I don't think having an X/Y problem is worthy of a downvote. In fact, it's the exact opposite. 

Someone needed to perform a task. They didn't know the best way to do it, so they attempted with X. X didn't work out well for them, due to one issue or another, so they ask the question. That's when people respond "Don't do X, do Y."

It's worth a downvote when they need to perform a task and they don't make any attempt at all...
