### ISSUE TITLE
[New Page] You did nothing

### ISSUE THREAD

**Issue by LindaLawton** [WillSullivan/idownvotedbecause#79]
I need a new page.    [offending question](https://stackoverflow.com/q/49670100/1841839)   in this case the user did not do any research or make any attempt.   I end up doing 

     http://idownvotedbecau.se/noattempt/ + http://idownvotedbecau.se/noresearch/

or 

    http://idownvotedbecau.se/noattempt/ ||  http://idownvotedbecau.se/noresearch/

I think we need a page that combines the two.   Something along the lines of your question does not appear to contain any effort.   

How do we write this without outright saying to people I cba to answer your question because you cba to try.

**Comment by WillSullivan** [comment]
:/ I think the person did some research on that question. They definitely did find some code that was slightly related. Hell, they even put in some effort, as they used that code and actually ran it. That's more effort than *a lot* of questions posted every day. Hell, they even included an exception message with enough details that even a PHP nothing like me knows what's wrong.

I think the big problem with that question is that the OP is just waaaaay in over their head. They're trying to attempt to program something that requires a good deal of understanding of not only the language and framework they're working with, but also with how complex external systems work (in this case, using Google Doc's API to interact with a spreadsheet contained within). 

This question is the definition of "too broad", as what they need to know and code would be a series of tutorials, not a single answer to a question. 

I'm not sure if there's any way IDVB can help to improve this situation because the real solution is for the OP to read some books, learn about different tools used in the process of supporting development of a program like this, and write a bunch of throwaway prototypes to learn how the pieces parts fit together. There's no helping improve their question, it's a goner, and needs to be deleted.

**Comment by LindaLawton** [comment]
Check his question preedit  he had nothing my comments promoted him to edit it to so your pages do work
